INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(150, 'Jamie', 'CEO', null);
INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(100, 'Alan', 'MANAGER', 150);
INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(400, 'Steve', 'MANAGER', 150);
INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(220, 'Martin', 'NORMAL', 100);
INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(275, 'Alex', 'NORMAL', 100);
INSERT INTO EMPLOYEE("EMP_ID", "NAME", "TYPE", "MANAGER_ID") VALUES(190, 'David', 'NORMAL', 400);
